baseURL = 'https://me.twttr.io/'
languageCode = 'en-us'
title = 'twttr.io'
theme = 'PaperMod'
disableKinds = ["RSS", "taxonomy", "term"]

[params]
author = "twttr"
defaultTheme = "auto"
showShareButtons = false
showReadingTime = true
showBreadCrumbs = false
showPostNavLinks = true
showCodeCopyButtons = true
showToc = true
disableSpecial1stPost = true

[params.profileMode]
enabled = true
title = "Hey, I'm twttr"
subtitle = "Software Engineer specializing in iOS & macOS development. Also building backends, frontends, and webOS apps."
imageUrl = "images/profile.jpg"
imageWidth = 150
imageHeight = 150

[[params.socialIcons]]
name = "github"
url = "https://github.com/twttr"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/twttr"

[outputs]
home = ["HTML"]

[markup.goldmark.renderer]
unsafe = true
